### PR TITLE
Fix GamePicker animation bug in Safari

### PR DESCRIPTION
**Pull request by michaelti**
Adds a useEffect to hide the "children" (i.e. the player icons) from the GamePicker component until it's done animating. Otherwise, it pops in and makes things janky in certain browsers.

### CODE REVIEW

**Comment by SammyAbukmeil** [comment]
Tested locally, seems to be working well on Safari and Chrome.

There's a slight overlap issues on very small devices (340px wide and below)

image

**Comment by michaelti** [comment]
@SammyAbukmeil Thanks! I can only repro that issue in Chrome (looks okay in Safari/Firefox). Will investigate.

**Comment by michaelti** [comment]
@SammyAbukmeil That should be fixed now.

**Review by SammyAbukmeil — APPROVED** [review]
Looks good to me!

**Pull request merged**
